### PR TITLE
add example of including module in application controller

### PR DESCRIPTION
**Pull request by mcfiredrill**
I admit, I got a little confused about this at first, I tried adding the module to the config/application.rb. 
Maybe an example would be helpful. ¯_(ツ)_/¯

### CODE REVIEW

**Comment by Davidslv** [comment]
:+1: I like examples

**Comment by spastorino** [comment]
I like examples too but this one I think is a bit misleading because if I'm not wrong ImplicitRender won't work in Rails API just by doing that.
Test it and let me know.

**Comment by jeremywadsack** [comment]
I had done this same thing based on the suggestion in [this SO post](http://stackoverflow.com/a/26848821/201911). However, I just tried removing that line (because of your comment @spastorino) and everything works just fine without it. I don't recall at this point what the issue was that I thought I was fixing with this, but it doesn't seem to make any difference having it in the code, so I don't think it's doing anything.

**Comment by spastorino** [comment]
Closing this PR because it's old and doesn't seem to help at this point. If you consider that there's some example worth adding, go ahead and open another PR and I will happily merge it 😄

**Pull request closed without merging**
