### PR TITLE
Removes rails 3 dependencies, 4.2.0 instead

### PR DESCRIPTION
**Pull request by Davidslv**
Hello,

With the move to version 0.4.0 I would like to suggest removing any rails 3.x dependencies.
I suggest 4.2.0 in this Pull Request but I'm happy to change it to other version.

I hope it makes sense.

Thank you

### CODE REVIEW

**Comment by Davidslv** [comment]
@steveklabnik is there anything you would like me to do in this PR ?
Thank you

**Comment by steveklabnik** [comment]
I'm not sure what ditching Rails 3 buys us, really.

**Comment by Davidslv** [comment]
@steveklabnik I think that everyone still has the chance of using rails-api on rails 3 by using the previous version.

I don't see why you would maintain two or three different versions of rails in this codebase, which is what's happening, there's code for rails 3, rails 4 and already conditionals for rails 5.

By removing what is old you are just avoid maintaining an unnecessary debt, that's why in my opinion we should remove that dependency. In the end of the day that's why `Gemfile` exists, to easily update old gem versions or keep in a specific one for any kind of reason.

Answering your question: The benefit in my opinion is less code to take care and maintain :smiley: 

Thank you

**Comment by ests** [comment]
+1. I believe that Rails' 3.2 lifespan is nearing the end. And this is nice step towards removing clutter.

**Comment by EduardoBautista** [comment]
You have committed a swap file by the way.

**Comment by Davidslv** [comment]
Thanks @EduardoBautista, I've just removed them.

**Comment by spastorino** [comment]
I'm thinking about this and I will close the PR for now until we conclude something.

**Pull request closed without merging**
